### ISSUE TITLE
Document how to use it

### ISSUE THREAD

**Issue by richkeenan** [FlexTradeUKLtd/jfixture-scala#2]
The README/Wiki should include some documentation on what this project does, how to use it etc...

@albx79 Maybe you'd be willing to help out as I'm not very familiar with Scala?

**Comment by albx79** [comment]
@richkeenan , thanks for publishing it! Yes I'll try to write something when I have time, hopefully next week. 

Also, I've just remembered that scala dependencies should be suffixed with the scala version used to compile them (2.11, in this case), and possibly compiled against several versions. I'll try to do that as well, if I have enough time...
