### ISSUE TITLE
JFixture / JFixture-Scala dependency management

### ISSUE THREAD

**Issue by philipwhiuk** [FlexTradeUKLtd/jfixture-scala#7]
I think we should consider either releasing `jfixture-scala` in parallel to `jfixture` or making it a `provided` dependency. As it is, just depending on `jfixture-scala` sort of works until you find a bug in the built-in `jfixture` version that's fixed in a newer release.

**Comment by pwfcurry** [comment]
https://github.com/FlexTradeUKLtd/jfixture-scala/commit/f09f9491368255aeb0dd4c916d1d8387ee7af2a8
